### ISSUE TITLE
floating decimals

### ISSUE THREAD

**Issue by gdarai** [zdanowiczkonrad/number-currency-format#1]
Thanks for making this awesome library.
All other solutions I found around the world are just too heavy and usually cannot do what I really need, this was perfect.

Almost.

What I am missing in this beautiful library is variable decimal length. Optional = only if the programmer wants to be able to write the decimal without any rounding.

1 => '1'
1.1 => '1.1'
1000.1 => '1,000.1'
1000.11 => '1,000.11'

Would it be possible to add it (not default, just optional)?
If you want I can suggest also the needed change in the code.

**Comment by zdanowiczkonrad** [comment]
I am glad you like it! there's such option: `decimalsDigits`. Please check the docs :)

**Comment by zdanowiczkonrad** [comment]
And here's the example in tests:
https://github.com/zdanowiczkonrad/number-currency-format/blob/master/test.js#L20

**Comment by gdarai** [comment]
Well that rounds to a specified length am I right?... but I want to be the number 'as it was' without the rounding.

**Comment by gdarai** [comment]
Something like:
```
    const opts = parseOptions(options);

    const roundedPrice = parseFloat(
            (opts.arithmeticalRounding ? roundToPlace(number, opts.decimalsDigits) : +number)
        .toString());

    const fullPriceInNormalFormat = opts.decimalsDigits >= 0 ?
      roundedPrice.toFixed(opts.showDecimals === SHOW_DECIMALS.NEVER ? 0 : opts.decimalsDigits) :
      roundedPrice.toString();
```
Instead of the code you have on line 77 - 81

**Comment by zdanowiczkonrad** [comment]
Can you give an example price and show how you expect it to be formatted?

**Comment by zdanowiczkonrad** [comment]
Ah, ok. Sorry I misunderstood you in the first place. so you want to have an option to show decimals in the original form, as is, for example from your code:
```
1 => '1'
1.1 => '1.1'
1000.1 => '1,000.1'
1000.11 => '1,000.11'
1000.111 => '1,000.111'
```
Am I right? Does that makes any sense business-wise (is there any actual locale and currency that needs that? Would appreciate any example :)

If that is a valid case, then absolutely that makes sense as a new feature. I'd recommend to add a new option: `SHOW_DECIMALS = 'AS_IS'`, like:
```js
format(10.1, { showDecimals: 'AS_IS' });
// -> 10.1
format(10.111, { showDecimals: 'AS_IS' });
// -> 10.111
format(10.0, { showDecimals: 'AS_IS' });
// -> 10 ? or 10.0?
format(10, { showDecimals: 'AS_IS' });
// -> 10
```
this will take precedence over `decimalsDigits`. Is that what you were thinking about?

I'd be more than happy welcome your contribution (proper tests included)! And thanks for your contribution so far!

**Comment by gdarai** [comment]
Well, it is not for currency only. I am working in Stock Exhange and we trade in points as well as in currencies... and points do need decimals.
And I need formating function which would help the user to read what he put into the input field no matter if he put in ```100'000'000``` (as EUR) or ```12.125``` as index points.

**Comment by gdarai** [comment]
And yes, the AS_IS what I am looking for. I will try to do the changes include the test and send you pull request.

**Comment by zdanowiczkonrad** [comment]
Would be awesome! And thanks for a good explanation, that makes perfect sense.

**Comment by zdanowiczkonrad** [comment]
Another feature you mentioned is unparsing the string to a number, right? We may consider that, but I am not sure this would be a part of this library given we want to make it super tiny and do one single job... but let's think about this! how would you see the API for that?

**Comment by gdarai** [comment]
Sure thing... thanks for considering the un-formating. I will star a separate issue for it since it is a separate thing.

**Comment by gdarai** [comment]
I am not allowed to commit a new branch... how would you prefer to get the contribution? Or should I ask for the permission somewhere?

**Comment by zdanowiczkonrad** [comment]
Please fork this repo and make a pull request out of a forked branch. That should work!

**Comment by gdarai** [comment]
Soo... it still has some issues, I forked using the button in top right,
But I cannot click the green button Create new PR, do you have any idea why?

**Comment by gdarai** [comment]
file:///home/martin/screenshot.png

**Comment by gdarai** [comment]
I also cannot insert pictures in any way so I cannot show you what I am talking about. But ok. The forked repo is here: https://github.com/gdarai/number-currency-format
