### ISSUE TITLE
Un-formating

### ISSUE THREAD

**Issue by gdarai** [zdanowiczkonrad/number-currency-format#2]
This issue should cover the functionality of un-formating which parses the formated number back to it's original. As suggested in #1.

So the idea is to have a pair function which would do '1,000' => 1000 or '1,000,000.23' => 1000000.23

You are right that it is another functionality. To have it in one library has only one huge advantage... you can have one formating definition for both operations.
Simple API would then be the same as for the format function:
unformatedValue = unformat(formatedText[, formatingOptions])

**Comment by zdanowiczkonrad** [comment]
Implemented in https://github.com/zdanowiczkonrad/number-currency-format/commit/dc89db25abe9122425d7ed4cacce09ba07e7e74f. Although I have concerns if this suits this library really.

**Comment by zdanowiczkonrad** [comment]
It can be extracted out of it anyway at some point.
