### ISSUE TITLE
Improving performance: string enums to use number values

### ISSUE THREAD

**Issue by gdarai** [zdanowiczkonrad/number-currency-format#3]
This is just an idea, since the goal is to have fast, lightweight library...

There are two string comparisons on the parameters: the showDecimals and currencyPosition.

Wouldn't it be faster to publish the corresponding maps: SHOW_DECIMALS and CURRENCY_POSITION, replace the string values in the maps with numbers and compare the numbers?

**Comment by zdanowiczkonrad** [comment]
I think it is ok to do this kind of improvements if:
- they bring significant performance improvement
or
- they make the code clearer

will any of this be true? I am afraid this is to little for the price of number encoding (that is usually more error-prone).

**Comment by gdarai** [comment]
ok, closing issue
