### ISSUE TITLE
Negative numbers with thousand separator is broken

### ISSUE THREAD

**Issue by gdarai** [zdanowiczkonrad/number-currency-format#5]
I have a bug for you, thousand separator should not be between minus and number:
Wrong -500 --> -,500.00
Right -500 --> -500.00

assert(format(-234.56, { thousandSeparator: ','}), '-234.56', 'Thousand separator works also in border case with negative sign');

The fix is to change line 56 to:
```const maybeSeparator = (index < numberText.length - 1 && (numberText.length - index - 1) % 3 === 0 && currentLetter!== '-') ? separator : '';```

**Comment by zdanowiczkonrad** [comment]
Good find! No support for negative numbers has been tested. Do you mind creating a pull request for that as well?

**Comment by zdanowiczkonrad** [comment]
I'll add that fix by myself.

**Comment by zdanowiczkonrad** [comment]
Fixed with https://github.com/zdanowiczkonrad/number-currency-format/commit/dc89db25abe9122425d7ed4cacce09ba07e7e74f.
